export const clerkAppearance = {
  variables: {
    colorPrimary: "hsl(17 100% 60%)",
    colorPrimaryForeground: "hsl(40 15% 3%)",
    colorBackground: "hsl(30 12% 9%)",
    colorNeutral: "hsl(40 35% 74%)",
    colorForeground: "hsl(40 35% 74%)",
    colorText: "hsl(40 35% 74%)",
    colorTextSecondary: "hsl(35 10% 65%)",
    colorInput: "hsl(30 15% 18%)",
    colorInputForeground: "hsl(40 35% 74%)",
    colorInputText: "hsl(40 35% 74%)",
    colorMuted: "hsl(30 15% 14%)",
    colorMutedForeground: "hsl(35 10% 65%)",
    colorBorder: "hsl(30 15% 20%)",
    colorRing: "hsl(17 100% 60%)",
    colorModalBackdrop: "rgba(0, 0, 0, 0.75)",
    fontFamily: "var(--font-sans)",
    fontFamilyButtons: "var(--font-sans)",
    borderRadius: "0.5rem",
  },
  elements: {
    rootBox: "text-foreground",
    cardBox: "drop-shadow-[0_16px_40px_rgba(0,0,0,0.55)]",
    card: "bezel panel-gradient border border-orange-200/20 bg-[#120d0a] text-foreground shadow-[0_20px_60px_rgba(0,0,0,0.55)]",
    headerTitle: "font-display tracking-wide text-orange-100",
    headerSubtitle: "text-muted-foreground",
    formFieldLabel: "text-muted-foreground",
    formFieldInput:
      "bg-input border-border text-foreground placeholder:text-muted-foreground focus:border-primary focus:ring-1 focus:ring-primary/40",
    formButtonPrimary:
      "bg-primary text-primary-foreground hover:bg-primary/85 focus-visible:ring-2 focus-visible:ring-primary/45",
    footerActionText: "text-muted-foreground",
    footerActionLink: "text-primary hover:text-secondary",
    dividerLine: "bg-border",
    dividerText: "text-muted-foreground",
    socialButtonsBlockButton: "border-border bg-card text-foreground hover:border-primary/35 hover:bg-muted/70",
    socialButtonsProviderIcon: "text-muted-foreground",
    modalBackdrop: "backdrop-blur-sm",
    modalContent:
      "bezel panel-gradient border border-orange-200/20 bg-[#120d0a] shadow-[0_25px_80px_rgba(0,0,0,0.65)]",
    avatarBox: "h-8 w-8 border border-orange-300/35",
    userButtonTrigger: "rounded-full focus:shadow-none focus-visible:ring-2 focus-visible:ring-primary/50",
    userButtonPopoverCard:
      "border border-orange-200/20 bg-[#120d0a]/98 !text-orange-100 shadow-[0_18px_50px_rgba(0,0,0,0.6)]",
    userButtonPopoverMain: "!text-orange-100",
    userButtonPopoverActions: "border-t border-border/70",
    userButtonPopoverActionButton:
      "!text-orange-100 hover:!text-orange-100 hover:!bg-orange-200/10",
    userButtonPopoverCustomItemButton:
      "!text-orange-100 hover:!text-orange-100 hover:!bg-orange-200/10",
    userButtonPopoverActionButtonIcon: "!text-orange-200/75",
    userButtonPopoverActionItemButtonIcon: "!text-orange-200/75",
    userPreviewMainIdentifier: "!text-orange-100",
    userPreviewSecondaryIdentifier: "!text-muted-foreground",
    menuItem: "!text-orange-100 hover:!bg-orange-200/10",
    userButtonPopoverFooter: "border-t border-border",
    userButtonPopoverFooterPagesLink: "text-muted-foreground hover:text-primary",
  },
} as const;
